// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

// @generated by enums.py

using System;

namespace Facebook.Yoga
{
    [Flags]
    public enum Errata : uint
    {
        None = 0,
        StretchFlexBasis = 1,
        AbsolutePositionWithoutInsetsExcludesPadding = 2,
        AbsolutePercentAgainstInnerSize = 4,
        All = 2147483647,
        Classic = 2147483646,
    }

    public static class ErrataExtensions
    {
        public static string ToString(Errata e)
        {
            return YGErrataToString((YGErrata)e);
        }

        private static string YGErrataToString(YGErrata errata)
        {
            switch (errata)
            {
                case YGErrata.YGErrataNone:
                    return "none";
                case YGErrata.YGErrataStretchFlexBasis:
                    return "stretch-flex-basis";
                case YGErrata.YGErrataAbsolutePositionWithoutInsetsExcludesPadding:
                    return "absolute-position-without-insets-excludes-padding";
                case YGErrata.YGErrataAbsolutePercentAgainstInnerSize:
                    return "absolute-percent-against-inner-size";
                case YGErrata.YGErrataAll:
                    return "all";
                case YGErrata.YGErrataClassic:
                    return "classic";
                default:
                    return "unknown";
            }
        }
    }

    internal enum YGErrata
    {
        YGErrataNone = 0,
        YGErrataStretchFlexBasis = 1,
        YGErrataAbsolutePositionWithoutInsetsExcludesPadding = 2,
        YGErrataAbsolutePercentAgainstInnerSize = 4,
        YGErrataAll = 2147483647,
        YGErrataClassic = 2147483646,
    }
}

